Fix the CI failure on Ruby 3.5
When running CI on Ruby 3.5, it fails as shown. As the error message indicates, rdoc was removed from the standard library, which caused the tests to fail. I fixed this by adding rdoc to the Gemfile.

```
/home/runner/work/timecop/timecop/Rakefile:4: warning: rdoc/task is found in rdoc, which is not part of the default gems since Ruby 3.5.0.
You can add rdoc to your Gemfile or gemspec to fix this error.
rake aborted!
LoadError: cannot load such file -- rdoc/task (LoadError)
/home/runner/work/timecop/timecop/Rakefile:4:in '<top (required)>'
/home/runner/work/timecop/timecop/vendor/bundle/ruby/3.5.0+4/gems/rake-13.3.1/exe/rake:27:in '<top (required)>'
/home/runner/.rubies/ruby-head/bin/bundle:25:in '<main>'
(See full trace by running task with --trace)
```